1073 make external callbacks optional
DiamondLightSource/hyperion pull request #1079
Opened 2024-01-16 16:05 UTC by dperl-dls

Fixes #1073

Requires GDA change https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40900 to take effect, but shouldn't break anything on its own

### To test:
1. Run tests
2. Run `hyperion_restart()` from GDA (with the above change applied) and see that hyperion is started with the external callbacks turned off

2024-01-17 14:48 UTC, DominicOram requested changes
Love all the additional typing, thanks! Could you add a couple of unit tests that cover the different behavior of `BlueskyRunner` depending on if the `use_external_callbacks` is set?

2024-01-17 14:48 UTC, DominicOram commented on run_hyperion.sh
> +    declare -A h_only_args=(        ["SKIP_STARTUP_CONNECTION"]="$SKIP_STARTUP_CONNECTION"
Could: Having just `h` here (and in the file as a whole) is not so obvious as to what you mean. Maybe `hyperion_main_only_args`?

2024-01-17 14:48 UTC, DominicOram commented on src/hyperion/experiment_plans/experiment_registry.py
> +    callback_collection_type: type[AbstractPlanCallbackCollection]
❤️

2024-01-18 12:55 UTC, DominicOram submitted a review, later dismissed

2024-01-23 16:39 UTC, olliesilvester approved these changes
Looks good - that extra test seems trustworthy

2024-01-24 10:29 UTC, merged