#1101 Wait for moves before FGS kickoff
DiamondLightSource/hyperion pull request #1112
Opened 2024-02-02 08:49 UTC by dperl-dls

Fixes #1101 

Link to dodal PR (if required): [#317](https://github.com/DiamondLightSource/dodal/pull/317)

Has already been tested on the beamline.

### To test:
1. See tests aren't failing.

2024-02-02 16:36 UTC, DominicOram requested changes
Thanks, minor comment

2024-02-02 16:36 UTC, DominicOram commented on src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +        yield from bps.wait()  # Wait for all moves with no assigned group
Should: The ordering of the logs here is deceptive. I think we should have two logs, one before the wait that logs basically the same as the comment then we log saying we're kicking off and do the kick off

2024-02-02 17:56 UTC, olliesilvester commented
Can we apply the same change to `panda_flyscan_xray_centre_plan` I know it's really annoying having to do everything twice, I'll try and get them merged soon!

2024-02-05 11:18 UTC, DominicOram approved these changes

2024-02-05 11:19 UTC, merged