Dodal 413 make common fgs
DiamondLightSource/hyperion pull request #1294
Opened 2024-04-05 17:07 UTC by olliesilvester

Fixes dodal  #[413](https://github.com/DiamondLightSource/dodal/issues/413)

Link to dodal PR (if required): #[422](https://github.com/DiamondLightSource/dodal/pull/422)
(remember to update `setup.cfg` with the dodal commit tag if you need it for tests to pass!)

I propose that, rather than changing `test_panda_flyscan_xray_centre`, I should make a PR on top of this one which combines the flyscan_xray_centre plans

### To test:
1. Do thing x
2. Confirm thing y happens

2024-04-12 13:54 UTC, rtuck99 commented on tests/conftest.py
I assume this is to be invoked separately from future tests and this commented out code can be removed?

2024-05-30 15:06 UTC, rtuck99 approved these changes
All ok - apart from comment re commented out code

2024-06-03 14:18 UTC, DominicOram requested changes
Just the one comment, thanks!

2024-06-10 11:41 UTC, DominicOram approved these changes
Great, thank you!

2024-06-11 07:33 UTC, merged