Use new params in XrayCentre
DiamondLightSource/hyperion pull request #1331
Opened 2024-04-24 14:25 UTC by dperl-dls

Building on #1330 uses the new params for the xraycentre plans

Towards #1289 

### To test:
1. Run tests

2024-04-30 08:19 UTC, rtuck99 commented on tests/test_data/new_parameter_json_files/test_gridscan_param_defaults.json
> +        "microns_per_pixel_x": 1.25,
Ditto comments in previous PR re microns_per_pixel

2024-05-13 15:15 UTC, DominicOram requested changes
Awesome, this is so much cleaner, particularly the `UpdateParams`. Some comments to make it a step cleaner but otherwise good.

2024-05-13 15:15 UTC, DominicOram commented on src/hyperion/external_interaction/callbacks/grid_detection_callback.py
> +    set_stub_offsets: bool
Should: Some of these parameters don't change from the grid detection so I don't think we need to have them in here at all. I can't see any reasonable way that we would want to change them based on an optical detection in the near future either:
* `set_stub_offsets`
* `transmission_frac`
* `exposure_time_s`

2024-05-13 15:15 UTC, DominicOram commented on src/hyperion/external_interaction/callbacks/grid_detection_callback.py
>  class GridDetectionCallback(CallbackBase):
Should: I don't think `run_up_distance_mm` is ever used here now so we can remove

2024-05-13 15:15 UTC, DominicOram commented on src/hyperion/parameters/gridscan.py
> +            detector_size_constants=self.detector,  # type: ignore
Could: Can you put a comment here that this should get tidied by https://github.com/DiamondLightSource/hyperion/issues/1307

2024-05-14 12:54 UTC, DominicOram approved these changes
Great, thanks. I've added a commit to take it a step further and remove stub offsets and exposure time as they're not used. Otherwise all looks good now!

2024-05-14 14:05 UTC, merged