1474 panda gridscan smargon speed
DiamondLightSource/hyperion pull request #1498
Opened 2024-07-24 09:32 UTC by rtuck99

Fixes #1474 

Corresponding save-panda cli utility:
Link to dodal PR (if required): DiamondLightSource/dodal#702

### To test:
1. Panda gridscans can be captured
2. tests pass

2024-08-02 12:25 UTC, olliesilvester requested changes
Looks mostly good, but the main comments:

- I don't think we need a separate pulse block. I also think we can combine the 'wait for position and send one pulse' and 'send all other pulses' steps.

- I know this was me originally, but I think we should try making the deadtime equal to what it says in the eiger manual, 100 ns

- I haven't looked at the yaml file in massive detail, but we should make sure the position part of this sequencer table is ignored now, like in `/dls_sw/i03/software/daq_configuration/panda_configs/flyscan_pcap_ignore_seq.yaml`. This was previously causing a race condition in the panda ioc, which has apparently been fixed now, but still better to be safe.

2024-08-02 12:25 UTC, olliesilvester commented on src/hyperion/device_setup_plans/setup_panda.py
> +        3. Send out the remaining x_steps - 1 triggers every time_between_steps_ms
Can we combine these two steps? Eg the second row could look like
repeats = num_pulses, trigger = POSA>POSITION, TIME1=exposure_time, TIME2=`time_between_x_steps`, outa1 = 1, outa2 = 0

2024-08-02 12:25 UTC, olliesilvester commented on src/hyperion/device_setup_plans/setup_panda.py
> +        3. Send out the remaining x_steps - 1 triggers every time_between_steps_ms
Same for 5 and 6

2024-08-02 12:25 UTC, olliesilvester commented on src/hyperion/device_setup_plans/setup_panda.py
> +    PULSE_WIDTH_US = 1
I believe we don't actually need a pulse block. The SEQ.OUT.A can be treated as our pulse, with width determined by `time1` and period determined by `time2`

2024-08-02 12:25 UTC, olliesilvester commented on src/hyperion/device_setup_plans/setup_panda.py
>          For a more detailed explanation and a diagram, see https://github.com/DiamondLightSource/hyperion/wiki/PandA-constant%E2%80%90motion-scanning
We need to update this too now :(

2024-08-06 12:34 UTC, rtuck99 commented on src/hyperion/device_setup_plans/setup_panda.py
> +
see args: section in docstring

2024-08-07 10:40 UTC, rtuck99 commented
Have simplified the sequence table but not removed the pulse generator or reduced the deadtime as discussed

2024-08-07 15:01 UTC, olliesilvester requested changes
I think this is in a testable state for tomorrow! I have a few more comments, but they're mostly nits

2024-08-07 15:10 UTC, olliesilvester approved these changes
Good to merge now I think, after that missing docstring is added

2024-08-07 15:59 UTC, merged